config/routes.rb
Rails.application.routes.draw do
  get  'register',  to: 'accounts#new',     as: 'register'
  post 'register',  to: 'accounts#create'
  get  'login',     to: 'sessions#new',     as: 'login'
  get  'logout',    to: 'sessions#destroy', as: 'logout'

  root to: 'dashboards#home'

  resources :accounts, except: [:index]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:create]
  resources :users
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  layout "login"
  skip_before_action :require_login
  skip_after_action :verify_authorized

  def create
    if params[:email].present?
      user = User.find_by_email(params[:email])
      user.send_password_reset
      redirect_to login_url, notice: "Email sent with instructions."
    else
      @error = "Enter your email address."
      render :new
    end
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, alert: "Your Password Reset has Expired.<br><br>Please request a " + link_to('new password reset', new_password_reset_path) + ".".html_safe
    elsif @user.update_attributes(params[:user].permit(:password))
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Password has been saved. You are now logged in."
    else
      render :edit
    end
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, 'Reset Password' %>
<h3>Choose Your New Password</h3>

<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissable text-left"><%= flash[:notice].html_safe %></div>
<% end %>

<% if @user.errors.any? %>
  <div class="alert alert-danger alert-dismissable mt-5">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user, url: password_reset_path(params[:id]) do |f| %>

  <div class="field">
    <%= f.password_field :password, class: 'form-control', placeholder: 'Choose a Password...', id: 'password', autocorrect: 'off', autocapitalize: 'off', spellcheck: 'off' %>
  </div>

  <button type="submit">Save New Password</button>

<% end %>




<div style="margin:40px 0;">
  Go back to <a href="/login">Login</a></p>
</div>

app/views/password_resets/new.html.erb
<% provide :title, 'Reset Password' %>
<h3 class="font-light mb-8 text-center">Password Reset</h3>


<% if @error.present? %>
  <div class="alert alert-red" role="alert">
    <p><%= raw @error %></p>
  </div>
<% end %>

<%= form_tag password_resets_path, method: :post, class: 'card' do %>

    <div class="text-grey-dark text-sm mb-6">
      <p class="">To reset your password, enter the email for your account.</p>
      <p class="">A link will be automatically emailed to you, allowing you to choose a new password.</p>
    </div>

    <div class="form-field">
      <%= label_tag :email, 'Email', class: 'form-label' %>
      <%= text_field_tag :email, params[:email], class: 'form-text', placeholder: 'Email', tabindex: 1 %>
    </div>

    <div class="form-actions">
      <%= button_tag 'Reset Password', type: 'submit', class: 'btn btn-blue' %>
    </div>
    <div class="text-grey-dark text-xs mt-6">
      &#8592; Back to
      <%= link_to 'Login', login_path %>
    </div>

<% end %>