config/routes.rb
Rails.application.routes.draw do
  get  'register',  to: 'accounts#new',     as: 'register'
  post 'register',  to: 'accounts#create'
  get  'login',     to: 'sessions#new',     as: 'login'
  get  'logout',    to: 'sessions#destroy', as: 'logout'

  root to: 'dashboards#home'

  resources :accounts, except: [:index]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:create]
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :account

  validates :account, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :email, with: /@/
  validates :password, length: { minimum: 8, maximum: 300 }, presence: true, on: :create
  validates :password, length: { minimum: 8, maximum: 300 }, allow_blank: true, on: :update
  validate :password_pwned?

  scope :ordered, -> { order(:created_at) }

  def password_pwned?
    return if password.blank?
    errors.add :password, :pwned if User.pwned_check(password) == 'pwned'
  end

  def self.pwned_check(password)
    return 'pwned' if password.blank?
    return 'pwned' if password == 'passwordpassword'
    return 'safe' if Rails.env.test?

    password_hash = Digest::SHA1.hexdigest(password).upcase
    begin
      require 'net/http'
      url = URI.parse "https://api.pwnedpasswords.com/range/#{password_hash[0,5]}"
      res = ::Net::HTTP.get_response(url)
    rescue StandardError => e
      Rails.logger.fatal "#{__FILE__}:#{__LINE__}: Couldn't check user's password against Have I Been Pwned. Maybe it's down.. or timing out: #{e.to_s}".bg_red
      return 'safe'
    end

    unless res.code == '200'
      Rails.logger.fatal "#{__FILE__}:#{__LINE__}: Couldn't check user's password against Have I Been Pwned. (Response Code #{res.code})".bg_red
      return 'safe'
    end

    return 'pwned' if res.body.include? password_hash.last(-5)
    'safe'
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    PasswordResetEmailJob.perform_later(id)
  end

  private

    def generate_token(column) # for password reset
      loop do
        self[column] = SecureRandom.urlsafe_base64
        break unless User.exists?(column => self[column])
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    authorize User
    @users = policy_scope(User)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    authorize User
    @user = current_user.account.users.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    authorize User
    @user = current_user.account.users.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    user_is_deleting_themselves = @user.id if current_user && current_user.id.eql?(@user.id)
    @user.destroy
    respond_to do |format|
      format.html do
        if user_is_deleting_themselves
          reset_session
          redirect_to logout_path, notice: "Your account was deleted."
        else
          redirect_to users_url, notice: 'User was successfully destroyed.'
        end
      end
      format.json do
        reset_session if user_is_deleting_themselves
        head :no_content
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(policy(User).permitted_attributes)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: 'card') do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :email, 'Email', class: 'form-label' %>
    <%= form.text_field :email, class: 'form-text' %>
  </div>

  <div class="form-field">
    <%= form.label :password, 'Password', class: 'form-label' %>
    <%= form.text_field :password, class: 'form-text' %>
  </div>

  <div class="form-actions">
    <%= form.submit nil, class: 'btn btn-blue mr-6' %>
    <%= link_to 'Discard', account_path(current_user.account_id), class: 'btn-link' %>
  </div>
<% end %>

app/views/users/_list.html.erb
<% @users.each do |user| %>
  <div>
    <%= user.email %>
    <%= link_to('Edit', edit_user_path(user)) if policy(user).update? %>
    <%= link_to('Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }) if policy(user).destroy? %>
  </div>
<% end %>


<div class="mt-3">
  <%= link_to 'Add a User', new_user_path, class: 'btn-sm btn-blue-outline' %>
</div>

app/views/users/edit.html.erb
<% provide :title, 'Editing User') %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% provide :title, 'Users' %>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= render 'list' %>

app/views/users/new.html.erb
<% provide :title, 'New User' %>
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<% provide :title, 'User' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', account_path(current_user.account_id) %>