config/routes.rb
Rails.application.routes.draw do
  get  'register',  to: 'accounts#new',     as: 'register'
  post 'register',  to: 'accounts#create'
  get  'login',     to: 'sessions#new',     as: 'login'
  get  'logout',    to: 'sessions#destroy', as: 'logout'

  root to: 'dashboards#home'

  resources :accounts, except: [:index]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:create]
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> - New App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application',               'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-grey-lighter">

    <div class="masthead">
      <div class="container center-pad">
        <div class="flex">
          <div class="w-1/2 tracking-tight">
            BAAM
          </div>
          <div class="w-1/2 text-right">
            <%= link_to account_path(current_user.account_id) do %>
              <i class="fal fa-user" title="Account"></i>
            <% end %>
            <%= link_to 'Logout', logout_path %>
          </div>
        </div>

      </div>
    </div>
    <div class="title">
      <div class="container center-pad">
        <%= yield :title %>
      </div>
    </div>
    <div class="content">
      <nav>
        <div class="container center-pad">
          <%= link_to 'Home', root_url %>
        </div>
      </nav>
      <main>
        <div class="container center-pad">

          <% if flash[:notice] || notice.present? %>
            <div class="alert alert-yellow" role="alert">
              <%= raw flash[:notice] || notice %>
            </div>
          <% end %>

          <%= yield %>

        </div>
      </main>
    </div>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application',               'data-turbolinks-track': 'reload' %>
  </head>

  <body class="flex bg-grey-lighter justify-center">

    <div class="p-4 px-3 py-10">
      <div class="w-full max-w-xs">
        <h1 class="text-center font-hairline text-blue-darker text-4xl mb-8">Next Visit</h1>
        <%= yield %>
        <p class="text-center text-grey-dark text-xs">
          All rights reserved.
        </p>
      </div>
    </div>
  </body>
</html>