config/routes.rb
Rails.application.routes.draw do
  get  'register',  to: 'accounts#new',     as: 'register'
  post 'register',  to: 'accounts#create'
  get  'login',     to: 'sessions#new',     as: 'login'
  get  'logout',    to: 'sessions#destroy', as: 'logout'

  root to: 'dashboards#home'

  resources :accounts, except: [:index]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:create]
  resources :users
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :users, dependent: :destroy

  attr_accessor :signup_email,
                :signup_password,
                :signup_detected_state,
                :signup_detected_country,
                :signup_detected_ip_address,
                :signup_detected_user_agent

  validates :name, presence: true

  # on create only
  validates :signup_email, presence: { message: 'Please enter your email' }, on: :create
  validates :signup_email, format: { with: %r{.+@.+\z}i, message: "The email you entered isn't an email address!" }, on: :create
  validate  :email_unique, on: :create
  validates :signup_password, length: { minimum: 8, maximum: 300, message: 'Password needs to be between 16 and 100 characters long' }, on: :create
  validate  :password_pwned?, on: :create

  private

    def email_unique
      return if signup_email.blank?
      errors.add :signup_email, 'Your email is already registered. Please login.' if User.find_by_email(signup_email.downcase).present?
    end

    def password_pwned?
      return if signup_password.blank?
      errors.add :signup_password, "Please choose a different password. That password is banned as it's too common." if User.pwned_check(signup_password) == 'pwned'
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  layout "login", only: [:new, :create]
  skip_before_action :require_login, only: [:new, :create]
  skip_after_action :verify_authorized, only: [:new, :create]

  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @users = policy_scope(@account.users).ordered
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    if @account.valid?
      ActiveRecord::Base.transaction do
        @account = Account.create! account_params
        @user = @account.users.create! email:    account_params[:signup_email],
                                      password: account_params[:signup_password]
      end
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Welcome.'
    else
      render :new
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to login_path, notice: 'Your account has been deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_user.account
      authorize @account
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(policy(Account).permitted_attributes)
    end
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true, class: 'card') do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :name, 'Name', class: 'form-label' %>
    <%= form.text_field :name, class: 'form-text' %>
  </div>

  <div class="form-actions">
    <%= form.submit 'Update Account', class: 'btn btn-blue mr-6' %>
    <%= link_to 'Discard', account_path(current_user.account_id), class: 'btn-link' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% provide :title, 'Editing Account' %>
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

app/views/accounts/new.html.erb
<% provide :title, 'Start Now' %>
<h3 class="font-light mb-8 text-center">Start now with <span class="font-semibold">New App</span></h3>


<%= form_with model: @account, local: true, class: 'card' do |form| %>

    <% if @account.errors.any? %>
      <div class="alert alert-red" role="alert">
        <p class="font-semibold">Please resolve the following <%= pluralize(@account.errors.count, "error") %>:</p>
        <ul>
        <% @account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.label :signup_email, 'Email', class: 'form-label' %>
      <%= form.text_field :signup_email, class: 'form-text', placeholder: 'Email' %>
    </div>

    <div class="form-field">
      <%= form.label :signup_password, 'Choose a Password', for: 'password', class: 'form-label' %>
      <%= form.password_field :signup_password, id: 'password', class: 'form-text', placeholder: 'Password' %>
    </div>

    <div class="form-field">
      <%= form.label :name, 'Your Business Name', class: 'form-label' %>
      <%= form.text_field :name, class: 'form-text', placeholder: 'ABC & Co.' %>
    </div>

    <%= form.hidden_field :signup_detected_state %>
    <%= form.hidden_field :signup_detected_country %>
    <%= form.hidden_field :signup_detected_ip_address %>
    <%= form.hidden_field :signup_detected_user_agent %>

    <div class="form-actions">
      <%= form.submit 'Start Now', class: 'btn btn-blue' %>
    </div>

<% end %>



<div class="text-center mt-8 mb-8">
  <p class="text-black text-sm mb-2">Already have an account?</p>
  <div><a href="/login" class="btn-sm btn-blue-outline">Login instead</a></div>
</div>

app/views/accounts/show.html.erb
<% provide :title, 'Account' %>

<h1 class="mb-6">Account</h1>
<div>
  <%= @account.name %>
  <span class="pl-3">
    <% if policy(@account).update? %>
      <%= link_to 'Edit', edit_account_path(@account) %>
    <% end %>
    <% if policy(@account).destroy? %>
      &middot; <%= link_to('Close Account', @account, method: :delete, data: { confirm: 'This will immediately delete ALL your data and close your account. Are you sure?' }) %>
    <% end %>
  </span>
</div>


<div class="mt-6">
  <h4>Users</h4>
  <%= render 'users/list' %>
</div>

<hr>

<h3>Stimulus JS Example</h3>

<div data-controller="hello" data-hello-name="Chris">
  <input data-target="hello.name" type="text" data-action="paste->hello#paste">
  <button data-action="click->hello#log">Log</button>
              <!--   event->controller#action -->
</div>